#!/bin/sh

cd ../spider-game
wasm-pack build --target web --out-name spider --out-dir ../home/three-d
cargo run --release "../home/three-d/spider.png"

cd ../home
rm three-d/.gitignore
rm three-d/*.d.ts
rm three-d/package.json
