#!/bin/sh

cd ../dust
wasm-pack build examples/effect --target web --out-name effect --out-dir ../../../home/three-d
#cargo run --example effect --release "../home/three-d/effect.png"

cd ../home
rm three-d/.gitignore
rm three-d/*.d.ts
rm three-d/package.json
