#!/bin/sh

cd ../Dust
wasm-pack build examples/wireframe --target web --out-name wireframe --out-dir ../../../home/dust
#cargo run --example wireframe --release "../home/dust/wireframe.png"

cd ../home
rm dust/.gitignore
rm dust/*.d.ts
rm dust/package.json
