#!/bin/sh

cd ../dust
wasm-pack build examples/imposters --target web --out-name imposters --out-dir ../../../home/three-d
#cargo run --example imposters --release "../home/three-d/imposters.png"

cd ../home
rm three-d/.gitignore
rm three-d/*.d.ts
rm three-d/package.json
