#!/bin/sh

cd ../dust
wasm-pack build examples/hello_world --target web --out-name hello_world --out-dir ../../../home/three-d
#cargo run --example hello_world --release "../home/three-d/hello_world.png"

cd ../home
rm three-d/.gitignore
rm three-d/*.d.ts
rm three-d/package.json
