#!/bin/sh

cd ../dust
wasm-pack build examples/triangle --target web --out-name triangle --out-dir ../../../home/three-d
cargo run --example triangle --release "../home/three-d/triangle.png"
wasm-pack build examples/lighting --target web --out-name lighting --out-dir ../../../home/three-d
cargo run --example lighting --release "../home/three-d/lighting.png"
wasm-pack build examples/statues --target web --out-name statues --out-dir ../../../home/three-d
cargo run --example statues --release "../home/three-d/statues.png"
wasm-pack build examples/texture --target web --out-name texture --out-dir ../../../home/three-d
cargo run --example texture --release "../home/three-d/texture.png"
wasm-pack build examples/fireworks --target web --out-name fireworks --out-dir ../../../home/three-d
cargo run --example fireworks --release "../home/three-d/fireworks.png"
wasm-pack build examples/mandelbrot --target web --out-name mandelbrot --out-dir ../../../home/three-d
cargo run --example mandelbrot --release "../home/three-d/mandelbrot.png"
wasm-pack build examples/wireframe --target web --out-name wireframe --out-dir ../../../home/three-d
cargo run --example wireframe --release "../home/three-d/wireframe.png"
wasm-pack build examples/forest --target web --out-name forest --out-dir ../../../home/three-d
cargo run --example forest --release "../home/three-d/forest.png"
wasm-pack build examples/fog --target web --out-name fog --out-dir ../../../home/three-d
cargo run --example fog --release "../home/three-d/fog.png"

cp -R examples/assets/ ../home/three-d/examples/assets/

cd ../home
rm three-d/.gitignore
rm three-d/*.d.ts
rm three-d/package.json

rm tri-mesh/.gitignore
rm tri-mesh/*.d.ts
rm tri-mesh/package.json