#!/bin/sh

cd ../dust
wasm-pack build examples/wireframe --target web --out-name wireframe --out-dir ../../../home/three-d
#cargo run --example wireframe --release "../home/three-d/wireframe.png"

cd ../home
rm three-d/.gitignore
rm three-d/*.d.ts
rm three-d/package.json
