#!/bin/sh

cd ../Dust
wasm-pack build examples/effect --target web --out-name effect --out-dir ../../../home/dust
#cargo run --example effect --release "../home/dust/effect.png"

cd ../home
rm dust/.gitignore
rm dust/*.d.ts
rm dust/package.json
