#!/bin/sh

cd ../dust
wasm-pack build examples/hello_world --target web --out-name hello_world --out-dir ../../../home/three-d
cargo run --example hello_world --release "../home/three-d/hello_world.png"
wasm-pack build examples/lighting --target web --out-name lighting --out-dir ../../../home/three-d
cargo run --example lighting --release "../home/three-d/lighting.png"
wasm-pack build examples/texture --target web --out-name texture --out-dir ../../../home/three-d
cargo run --example texture --release "../home/three-d/texture.png"
wasm-pack build examples/effect --target web --out-name effect --out-dir ../../../home/three-d
cargo run --example effect --release "../home/three-d/effect.png"
wasm-pack build examples/wireframe --target web --out-name wireframe --out-dir ../../../home/three-d
cargo run --example wireframe --release "../home/three-d/wireframe.png"
wasm-pack build examples/imposters --target web --out-name imposters --out-dir ../../../home/three-d
cargo run --example imposters --release "../home/three-d/imposters.png"
wasm-pack build examples/mesh_tools --target web --out-name mesh_tools --out-dir ../home/three-d

cp -R examples/assets/ ../home/three-d/examples/assets/

cd ../spider-game
wasm-pack build --target web --out-name spider --out-dir ../home/three-d
cargo run --release "../home/three-d/spider.png"

cd ../tri-mesh
wasm-pack build examples/mesh_tools --target web --out-name mesh_tools --out-dir ../../../home/tri-mesh
cargo run --example mesh_tools --release "../home/tri-mesh/mesh_tools.png"

cd ../bead-designer
wasm-pack build --target web --out-name bead --out-dir ../home/three-d
cargo run --release "../home/three-d/bead.png"

cd ../home
rm three-d/.gitignore
rm three-d/*.d.ts
rm three-d/package.json

rm tri-mesh/.gitignore
rm tri-mesh/*.d.ts
rm tri-mesh/package.json