#!/bin/sh

cd ../Dust
wasm-pack build examples/lighting --target web --out-name lighting --out-dir ../../../home/dust
#cargo run --example lighting --release "../home/dust/lighting.png"

cd ../home
rm dust/.gitignore
rm dust/*.d.ts
rm dust/package.json
