#!/bin/sh

cd ../tri-mesh
wasm-pack build examples/mesh_tools --target web --out-name mesh_tools --out-dir ../../../home/tri-mesh
cargo run --example mesh_tools --release "../home/tri-mesh/mesh_tools.png"

cd ../home
rm tri-mesh/.gitignore
rm tri-mesh/*.d.ts
rm tri-mesh/package.json
