#!/bin/sh

cd ../three-d
rm pkg/*

for EXAMPLE in triangle fireworks shapes2d shapes screen volume texture mandelbrot logo image fog picking normals wireframe sprites forest environment pbr lighting lights statues
do 
    export THREE_D_SCREENSHOT="../asny.github.io/three-d/$1/$EXAMPLE.png"
    if [ $EXAMPLE == fireworks ]; then
        export THREE_D_EXIT=1500
    else
        export THREE_D_EXIT=0
    fi
    cargo run --example $EXAMPLE --release --features image
    
    wasm-pack build examples/$EXAMPLE --target web --out-dir ../../pkg
    
    mv pkg/*.js ../asny.github.io/three-d/$1/
    mv pkg/*.wasm ../asny.github.io/three-d/$1/
    rm pkg/*
done

mkdir ../asny.github.io/three-d/$1/examples
mkdir ../asny.github.io/three-d/$1/examples/assets
cp -R examples/assets/ ../asny.github.io/three-d/$1/examples/assets/
