#!/bin/sh

VERSION=0.12

cd ../three-d/examples

for EXAMPLE in `ls -d *`
do 
    if [ $EXAMPLE != 'README.md' ] && [ $EXAMPLE != 'assets' ]
    then
        cd $EXAMPLE
        cargo update
        cargo clean
        cd ..
    fi
done
